export const defaultElementState = {
    colour: 'blue',
    position: [100, 100],
    width: 100,
    height: 100,
    angle: 0,
    borderWidth: 0,
    borderStyle: 'solid',
    borderColor: '',
    borderRadius: 0,
    zIndex: 0,
    blendMode: 'normal',
    text: '',
    font: '',
    fontStyle: '',
    fontSize: 50,
    fontWeight: '',
    textColour: '',
    textPosition: [0, 0] as [number, number],
    shadowXYOffset: [0, 0] as [number, number],
    shadowSpread: 0,
    shadowBlur: 0,
    shadowColor: '',
    shadowInset: false,
    textShadowXYOffset: [0, 0] as [number, number],
    textShadowBlur: 0,
    textShadowColor: '',
};